apiVersion: v1
kind: Service
metadata:
  name: {{ include "timekube.fullname" . }}
  labels:
    {{- include "timekube.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    {{- include "timekube.selectorLabels" . | nindent 4 }}
